# Generated by Django 4.0.6 on 2022-10-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0003_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', primary_key=True, serialize=False),
        ),
    ]
